命令稿啟動於 2017年03月13日 星期一 20:21:54
]0;rainwind@ubuntu: ~rainwind@ubuntu:~$ whoami;pwd
rainwind
/home/rainwind
]0;rainwind@ubuntu: ~rainwind@ubuntu:~$ git config -l
user.name=rainfallman
user.email=max7400641@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
]0;rainwind@ubuntu: ~rainwind@ubuntu:~$  git clone https://github.com/<your github account>/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gitr/lab1.gita/lab1.giti/lab1.gitn/lab1.gitf/lab1.gita/lab1.gitl/lab1.gitl/lab1.gitm/lab1.gita/lab1.gitn/lab1.git[C[C[C[C[C[C[C[C[C
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
]0;rainwind@ubuntu: ~rainwind@ubuntu:~$ exit

命令稿已於 2017年03月13日 星期一 20:23:27
 完成